// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:8027d7c2-f775-4dfd-b5ac-225212a6d8bc',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': 'b989e0cf5a234265878236e305bb806d',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'd01f9216-96a6-4d3c-b222-4cac7ae1a451',
    'aws_project_name': 'Graco',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'graco-mobilehub-1517832045',
}

export default awsmobile;
